## Neural Network

Backpropagation (short for "backward propagation of errors") is the algorithm that enables neural networks to learn. It’s used to update the weights in a network so that it gets better at making predictions.

### Step 1: Implementing a Simple Neural Network (Without Backpropagation Yet)

Before we introduce backprop, let’s first build a basic neural network with forward propagation.

This will help us see how data flows forward before we start calculating gradients.

#### Python Code: Forward Pass in a Simple Neural Network
We'll implement a 2-layer neural network with one hidden layer.

In [7]:
import numpy as np 

# sigmoid activation function
def sigmoid(x):
    return 1/(1 + np.exp(-x))

# Derivative of sigmoid (needed later for backpropagation)
def sigmoid_derivative(x):
    return x * (1 - x)

# Sample input (2 features)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  # Input data
y = np.array([[0], [1], [1], [0]])  # Expected output (XOR problem)

# Initialize weights randomly
np.random.seed(42)
input_layer_neurons = 2
hidden_layer_neurons = 2
output_neurons = 1

# Randomly initializing weights
W1 = np.random.uniform(size=(input_layer_neurons, hidden_layer_neurons))
W2 = np.random.uniform(size=(hidden_layer_neurons, output_neurons))

# Forward Propagation
hidden_layer_input = np.dot(X, W1)  # Input to hidden layer
hidden_layer_output = sigmoid(hidden_layer_input)  # Activation function

output_layer_input = np.dot(hidden_layer_output, W2)  # Input to output layer
output = sigmoid(output_layer_input)  # Activation function

print("Predicted Output (Before Training):")
print(output)

Predicted Output (Before Training):
[[0.53892274]
 [0.55132394]
 [0.5510619 ]
 [0.56117033]]


### Step 2: Loss Function & Understanding Gradient Descent

Now that we’ve implemented forward propagation, it’s time to measure how wrong our neural network’s predictions are. This is where the loss function comes in.

A loss function calculates the difference between the predicted output and the actual target. Our goal is to minimize this loss so that the neural network makes better predictions.

For a binary classification task, the most commonly used loss function is the Mean Squared Error (MSE) or Binary Cross-Entropy (Log Loss).
For now, we’ll use MSE, which is simple and works well for small networks.

Gradient Descent is the algorithm that helps adjust the weights of our network in a way that reduces the loss.

#### Python Code: Adding Loss Calculation

Now, let’s modify our forward propagation code to include loss calculation.

In [8]:
import numpy as np

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Mean Squared Error (MSE) Loss Function
def mse_loss(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

# Sample input (2 features)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  # Input data
y = np.array([[0], [1], [1], [0]])  # Expected output (XOR problem)

# Initialize weights randomly
np.random.seed(42)
W1 = np.random.uniform(size=(2, 2))  # Weights for input to hidden layer
W2 = np.random.uniform(size=(2, 1))  # Weights for hidden to output layer

# Forward Propagation
hidden_layer_input = np.dot(X, W1)  # Input to hidden layer
hidden_layer_output = sigmoid(hidden_layer_input)  # Activation function

output_layer_input = np.dot(hidden_layer_output, W2)  # Input to output layer
output = sigmoid(output_layer_input)  # Activation function

# Calculate loss
loss = mse_loss(y, output)

print("Predicted Output (Before Training):")
print(output)
print("\nLoss (Before Training):", loss)


Predicted Output (Before Training):
[[0.53892274]
 [0.55132394]
 [0.5510619 ]
 [0.56117033]]

Loss (Before Training): 0.2520513692725072


### Step 3: Understanding the Math Behind Backpropagation

Backpropagation is an algorithm used to compute the gradients of the loss function with respect to the weights and biases of the network.
It helps us determine how much each weight contributed to the error, so we can update them accordingly.

It consists of two main steps:

    1) Forward Pass → Compute predictions & loss.
    
    2) Backward Pass (Backpropagation) → Compute gradients & update weights.

In [9]:
import numpy as np

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

# Mean Squared Error (MSE) Loss Function
def mse_loss(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

# Sample input (2 features)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  # Input data
y = np.array([[0], [1], [1], [0]])  # Expected output (XOR problem)

# Initialize weights randomly
np.random.seed(42)
W1 = np.random.uniform(size=(2, 2))  # Weights for input to hidden layer
W2 = np.random.uniform(size=(2, 1))  # Weights for hidden to output layer

# Learning rate
learning_rate = 0.5

# Training loop
epochs = 10000  # Number of iterations
for epoch in range(epochs):
    # **Forward Propagation**
    hidden_layer_input = np.dot(X, W1)  # Input to hidden layer
    hidden_layer_output = sigmoid(hidden_layer_input)  # Activation function

    output_layer_input = np.dot(hidden_layer_output, W2)  # Input to output layer
    output = sigmoid(output_layer_input)  # Activation function

    # **Compute Loss**
    loss = mse_loss(y, output)

    # **Backward Propagation**
    # Compute gradient for output layer
    output_error = y - output
    output_delta = output_error * sigmoid_derivative(output)

    # Compute gradient for hidden layer
    hidden_layer_error = output_delta.dot(W2.T)
    hidden_layer_delta = hidden_layer_error * sigmoid_derivative(hidden_layer_output)

    # **Update Weights**
    W2 += hidden_layer_output.T.dot(output_delta) * learning_rate
    W1 += X.T.dot(hidden_layer_delta) * learning_rate

    # Print loss every 1000 epochs
    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss: {loss}")

print("\nFinal Predicted Output After Training:")
print(output)


Epoch 0, Loss: 0.2520513692725072
Epoch 1000, Loss: 0.1586043938154397
Epoch 2000, Loss: 0.07477982865962356
Epoch 3000, Loss: 0.04564895718379279
Epoch 4000, Loss: 0.031960089934838794
Epoch 5000, Loss: 0.024253118171967437
Epoch 6000, Loss: 0.0193892707812152
Epoch 7000, Loss: 0.016071864833796197
Epoch 8000, Loss: 0.013679104505030588
Epoch 9000, Loss: 0.011879164486818524

Final Predicted Output After Training:
[[0.05432736]
 [0.89823995]
 [0.89824011]
 [0.13514441]]
